camera_node_name: "cameranode"
image_topic_name: "/3d_image/image_raw"
depthImage_topic_name: "/3d_image/image_raw_depth"
pointCloud_topic_name: "/3d_image/3d_cloud"
cameraInfo_topic_name: "/3d_image/camera_info"
coordinates_of_target: "/target_coordinates"
cameraPoseTF: "camera_coordinate_system"
maskedDepth_topic: "/masked_depth_images"
obstacle_list_topic: "/obstacle_centers"
lineofsight_topic_name: "/line_of_sight"